### ISSUE TITLE
Propiedades compradas - tipo

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#1]
Utilizar el tipo Propiedad para determinar el tipo de propiedades compradas

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L9

**Comment by LU-MASACARO** [comment]
Se modificó el código en base a esta recomendación.
