### ISSUE TITLE
cantidadPropiedadesDePrecio - Abstracción de lógica

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#10]
Hay bastante lógica metida dentro de la misma función, capaz quede más declarativo si separás en distintas funciones las cosas que hace ésta.

Ej. abstraer en una función "preciosDePropiedades" el `map snd ...`. 

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/9be6ce5fc26a2e67234389fb920782eeb30e80ba/TP1/src/Monopoly.hs#L51-L52

**Comment by LU-MASACARO** [comment]
Se abstrajo lógica a una función llamada "preciosDePropiedadesCompradas" como se sugiere.
