### ISSUE TITLE
calculoFinal

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#11]
- Hay una repetición de lógica al pedir la última ronda a ambos participantes y su dinero, estaría bueno abstraer esa lógica
- ¿Es un calculo `calculoFinal`? Estaria más expresivo si mejor es una verificación o `tieneMayorPlataEnUltimaRondaQue`, por ejemplo

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/9be6ce5fc26a2e67234389fb920782eeb30e80ba/TP1/src/Monopoly.hs#L60-L61

**Comment by LU-MASACARO** [comment]
Se creó la función "cantidadDeDineroEnUltimaRonda" para abstraer lógica y se modifico el nombre de la función "calculoFinal" por "tieneMayorPlataEnUltimaRondaQue".
