### ISSUE TITLE
Parentesis - precedencia

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#12]
¡Ojo con los parentesis! Hay un par de lados donde están de más ya que la precedencia ya está bien!

Seguro algunos quedaron por el cambio a composiciones en algunas funciones :p, los dejo marcados:

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L40

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L61

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L64

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L80

De estas ultimas dos quiero notar que las funciones que están aplicando al participante pueden ser usadas componiendo!

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L92

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L55

**Comment by LU-MASACARO** [comment]
Se eliminaron paréntesis innecesarios.
