### ISSUE TITLE
Declaratividad en el cálculo de alquileres

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#13]
Mirando un poco la solución:

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L54-L55

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L60-L61

Y viendo lo que nos pide el ejercicio:

```
cobrarAlquileres: suma $10 por cada propiedad barata y $20 por cada propiedad cara obtenida. 
Las propiedades baratas son aquellas cuyo precio es menor a $150.
```

¿No hay algo raro en la solución, en parte por la declaratividad? Si bien se entiende que se están obteniendo las cantidades menores y mayores a $150, hay bastante lógica algorítmica (filtrar las propiedades mediante un precio definido, obtener la cantidad de propiedades, y a eso multiplicarlo por su valor).

Para hacerlo más declarativo, se podría empezar dividiendo en partes mas pequeñas el problema:
`Las propiedades baratas son aquellas cuyo precio es menor a $150.`
`Las propiedades baratas valen $10, las propiedades caras valen $20.`
`cobrarAlquileres suma al participante los valores de los alquileres de sus propiedades.`

Al dividirlo así, ¡Se pueden hacer funciones que me ayuden a solucionar el problema de una manera más declarativa! Tomando estas premisas, podriamos hacer 3 funciones:

`esPropiedadBarata`
`valorAlquiler`
`cobrarAlquileres`

Te dejo que intentes resolverlo con estas 3 funciones!

**Comment by LU-MASACARO** [comment]
Se usan las tres funciones solicitadas para que quede más declarativo.
