### ISSUE TITLE
verificacion de accionista - Se repite

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#14]
Ojo que se está repitiendo la verificación de si es accionista en dos lugares:

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L46

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L87

una función `esAccionista` ayudaria a resolver el problema!

**Comment by LU-MASACARO** [comment]
Se agregó la función "esAccionista" para evitar repetir lógica.
