### ISSUE TITLE
agregar accion de gritar en berrinche

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#15]
No para cambiar, sino algo a notar que se me pasó, en el enunciado indica que se la hace gritar a la persona, esto implica hacer que la persona grite y no agregar gritar a sus acciones. Igual lo considero correcto :p

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/f2a9d5f65c61850ee99fb83dbcc1e5e34a20b404/TP1/src/Monopoly.hs#L92

**Comment by LU-MASACARO** [comment]
Ahora a parte de agregar gritar a sus acciones, grita cada vez que hace berrinche.
