### ISSUE TITLE
Consulta Milhouse

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#16]
Esta consulta debería ser con variable anónima, ya que no nos interesa a quién odia Milhouse.

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/3d48957caee18247375912d4d3db6deeb03a2934/TP2/TP1-Logico.pl#L40

**Comment by LU-MASACARO** [comment]
Se cambió la consulta por una que utiliza variable anónima.
