### ISSUE TITLE
mapper de Dinero

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#2]
¡Buen uso de un mapper!

Algo que quiero notar de esta función: ¿Es necesario pasarle una cantidad a este mapper?

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L28-L29

Esta pregunta surge por cómo quedó `enojarse`. Si no se pasa una cantidad y se aplica parcialmente la función (+), se podrían componer los mappers! (Previo a modificar las posiciones de los parametros del mapper de modificar acciones) 

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L57

**Comment by LU-MASACARO** [comment]
Se modificó el orden en que se piden los parámetros de los mappers y se usó composición en la función "enojarse".
