### ISSUE TITLE
modificarAcciones - Expresividad

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#3]
Pondría mejor algo como `agregarAccionAJugador`, indica mejor qué hace la función.

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L31-L32

**Comment by LU-MASACARO** [comment]
Se tomó en cuenta la recomendación y se cambió el nombre de la función.
