### ISSUE TITLE
propiedadesDeParticipante - repetición de lógica

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#4]
Hay una repetición de lógica en estas dos funciones. Se podría abstraer la lógica de tomar el length, filtrar por una función y mapear al snd de la propiedad.

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L43-L47

**Comment by LU-MASACARO** [comment]
Se unificó a una sola función llamada "cantidadPropiedadesDePrecio" .
