### ISSUE TITLE
Utilizar mapper de propiedad

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#5]
Si hay un mapper de propiedad, se podrían componer los mappers modificarDinero y el mapper de propiedad y queda más declarativo esta función.

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L50

**Comment by LU-MASACARO** [comment]
Se creó el mapper correspondiente y se utilizó composición.
