### ISSUE TITLE
pasarPorElBanco - mapper tactica

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#6]
Siguiendo la misma lógica que en el issue #5 , con un mapper se pueden componer
https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L54

**Comment by LU-MASACARO** [comment]
Se tomaron las mismas acciones que en el issue #5 pero con la función "modificarTactica".
