### ISSUE TITLE
cobrarAlquileres - abstraer

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#7]
Abstraería el calculo de obtención de los valores de alquileres a otra función para que quede más declarativa
https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L66-L67

**Comment by LU-MASACARO** [comment]
Se abstrajo el cálculo de los alquileres a una función auxiliar.
