### ISSUE TITLE
Juego Final

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#8]
- Ojo con la repetición de lógica en la obtención de la cantidad del dinero de la última ronda de los participantes.

- Ojo con los retornos de strings. Si bien está bueno para verlo en la consola, lo que era necesario es retornar al jugador.

Puede parecer rara esta corrección, pero está bueno dividir lo que es la parte lógica con la parte de presentación. Por ejemplo, si se pidiera modificar las acciones del jugador ganador de la ronda, ¿Lo podría hacer con esta función?

Lo que sí se podría realizar es una función que retorne un String mostrando quién es el jugador ganador, para mostrarlo en pantalla, y esta función es la que se utiliza de manera de "presentación" en consola (no es pedida en el TP pero a modo de ejemplo)

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/594644e1305d31aa02f103d1b04b1e20a95c7ce5/TP1/src/Monopoly.hs#L80-L83

**Comment by LU-MASACARO** [comment]
Se utilizó una función auxiliar para no repetir lógica en la guarda y la función "juegoFinal" ahora devuelve al participante ganador.
