### ISSUE TITLE
Utilizar Composición

### ISSUE THREAD

**Issue by Maxi-F** [LU-MASACARO/Paradigmas-De-Programacion#9]
Hay un par de lugares donde hay bastantes paréntesis, estaría bueno cambiarlo con composiciones!

Dejo marcado en este issue algunos lugares donde estaria bueno cambiarlo:

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/9be6ce5fc26a2e67234389fb920782eeb30e80ba/TP1/src/Monopoly.hs#L42-L43

https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/9be6ce5fc26a2e67234389fb920782eeb30e80ba/TP1/src/Monopoly.hs#L86

(Ver issue #10 del siguiente tambien!)
https://github.com/LU-MASACARO/Paradigmas-De-Programacion/blob/9be6ce5fc26a2e67234389fb920782eeb30e80ba/TP1/src/Monopoly.hs#L51-L52

**Comment by LU-MASACARO** [comment]
Se eliminaron los paréntesis de algunas funciones mediante el uso de composición.
